config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  scope module: 'authors' do 

  get "/posts", to: "posts#index"
  get "/posts/new", to: "posts#new"
  post "/posts", to: "posts#create"
  get "posts/:id", to: "posts#show", as: "post"

  delete '/posts/:id', to: 'posts#destroy', as: "delete"
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts 
end

app/models/comment.rb
class Comment < ActiveRecord::Base 





end 

app/models/post.rb
class Post < ActiveRecord::Base 
belongs_to :author
has_rich_text :body



end 

app/models/user.rb
class User < ActiveRecord::Base 
    #has_many :posts
    has_secure_password
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }



end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    
end

app/controllers/authors/posts_controller.rb
module Authors
    class PostsController < AuthorsController


    def index 
        @posts = Post.all
    end 



    def new 
        @post = current_author.posts.build

    end 


    def create
        @post = current_author.posts.build(post_params)
        if @post.save  
            redirect_to posts_path
        else
            render :new 
        end 
    end 



    def show 
        @post = Post.find(params[:id])
    end 

    def destroy
        @post.destroy
        redirect_to posts_path
    end



    private
    
    def post_params
        params.require(:post).permit(:title, :body, :content)
    end

    end 
end 

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :authenticate_author!

    layout 'authors'

end 

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
    @posts = Post.all
end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/posts/index.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">Why Software Engineering?</h1>
          <p class="lead my-3">I am excited to be able to share my thoughts and experiences with you in this first post. This is out of my comfort zone, but I feel great about my learning</p>
          <p class="lead mb-0"><a href="/posts/3" class="text-white font-weight-bold">Continue reading...</a></p>
        </div>
      </div>
 <div class="wrapper">     
<h2 class="heading">Tips & Experiences </h2>

<% @posts.each do |post| %>

<div class="article"><%= link_to post.title, post_path(post) %></div>


<% end %>
</div>

app/views/authors/posts/new.html.erb
<h2 class="heading"> Create New Post </h2><br>

<div class="form-format"><%= form_for @post do |f| %>
<%= f.label :title, "Title of Post"  %><br>
<%= f.text_field :title %>
<br>
<br>
<%= f.label :body, "Content" %><br>
<%= f.rich_text_area :body %>
<br>
<br> 


<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<%= f.submit "Submit Post" %>

<% end %></div>

app/views/authors/posts/show.html.erb
<%= @post.title %><br><br>
<%= @post.body %><br>


<%= link_to "Delete Post", delete_path(@post), :method => :delete %><br>
<%= link_to 'Back', :back %>

app/views/home/_header.html.erb

    

      <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div>
          <div id="logo">
        <img src="assets/transparent-banner.png" alt="ShemaxCodes">
</div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="/authors/sign_up">Sign up</a>
          </div>
        </div>
      </header>


      <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="#">About</a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="/posts">All Posts</a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#">Connect with Me!</a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#">Portfolio</a>
          <a class="p-2 text-muted" href="#"></a>
    

        </nav>

app/views/home/index.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">Why Software Engineering?</h1>
          <p class="lead my-3">I am excited to be able to share my thoughts and experiences with you in this first post. This is out of my comfort zone, but I feel great about my learning</p>
          <p class="lead mb-0"><a href="/posts/3" class="text-white font-weight-bold">Continue reading...</a></p>
        </div>
      </div>
 <div class="wrapper">     
<h2 class="heading">Tips & Experiences </h2>

<% @posts.each do |post| %>

<div class="article"><%= link_to post.title, post_path(post) %></div>


<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <head>
    <title>ShemaxCodes</title>
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital@1&family=Source+Sans+Pro&display=swap" rel="stylesheet">
  
  
    <style>
  * {
    margin: 0;
    padding: 0;
}
  /*date color: #96D4CC;
  h2 color: #2c3e50;
  font source sans pro
  */
  
  
  body {
    background: #ffffff;
    margin: 20px auto;
    border-width: 25px;
    border-radius: 15px;
    font-family: 'Source Sans Pro', sans-serif;
  
  }
  


logo {
    max-width: 100%;
    height: 400;
    width: auto; 
}
    

 img {
  width: 96%;
 }

 h2 {
    color: #FDD1D2;
    font-family: 'Playfair Display', serif;
  }
  
  .date {
    text-transform: uppercase;
    color: #95D2CA;
  }
  
  
  .line1 {
    border-left: 5px solid #D4BBDD;
    padding-left: 5px;
    padding: 20px;
    width: 700px;
  
  }

  #.image-header {
    #margin: 20px auto;
    #border: 5px solid #FBEDE0;
    #background: #FBEDE0;
  #}

  .article {
    margin: 20px auto;
    padding: 20px;
    width: 700px;
  }


p {
  text-align: justify;
}

  .wrapper {
    margin: 20px auto;
    padding: 20px;
    width: 700px;
    position: center;

}
.blog-header {
    line-height: 1;
    border-bottom: 1px solid #e5e5e5;
}
.py-3 {
    padding-bottom: 1rem!important;
    padding-top: 1rem!important;
}

.nav-scroller .nav {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: nowrap;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
}

.bg-dark {
    background-color: #96d4cc!important;
}

.heading {
  text-align: center;
}

.form-format {
  text-align: center;
}


.article {
  display: inline-block;
  width: 160px;
  height: 100px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}


  </style>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= render 'home/header'%>

  <div class="container-two">
      <%= yield %>
  </div>

  

<footer class="branding">
  <small>&copy; 2021 <strong>MicheTek, LLC</strong> - Built with Ruby on Rails, JS, Boostrap</small>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>


  <head>
    <title>ShemaxCodes</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital@1&family=Source+Sans+Pro&display=swap" rel="stylesheet">
  
  
    <style>
  * {
    margin: 0;
    padding: 0;
}
  /*date color: #96D4CC;
  h2 color: #2c3e50;
  font source sans pro
  */
  
  
  body {
    background: #ffffff;
    margin: 20px auto;
    border-width: 25px;
    border-radius: 15px;
    font-family: 'Source Sans Pro', sans-serif;
  
  }
  


logo {
    max-width: 100%;
    height: 400;
    width: auto; 
}
    

 img {
  width: 96%;
 }

 h2 {
    color: #FDD1D2;
    font-family: 'Playfair Display', serif;
  }
  
  .date {
    text-transform: uppercase;
    color: #95D2CA;
  }
  
  
  .line1 {
    border-left: 5px solid #D4BBDD;
    padding-left: 5px;
    padding: 20px;
    width: 700px;
  
  }

  #.image-header {
    #margin: 20px auto;
    #border: 5px solid #FBEDE0;
    #background: #FBEDE0;
  #}

  .article {
    margin: 20px auto;
    padding: 20px;
    width: 700px;
  }


p {
  text-align: justify;
}

  .wrapper {
    margin: 20px auto;
    padding: 20px;
    width: 700px;
    position: center;

}
.blog-header {
    line-height: 1;
    border-bottom: 1px solid #e5e5e5;
}
.py-3 {
    padding-bottom: 1rem!important;
    padding-top: 1rem!important;
}

.nav-scroller .nav {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: nowrap;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
}

.bg-dark {
    background-color: #96d4cc!important;
}

.heading {
  text-align: center;
}

.form-format {
  text-align: center;
}


.article {
  display: inline-block;
  width: 160px;
  height: 100px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
  </style>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div>
          <div id="logo">
        <img src="assets/transparent-banner.png" alt="ShemaxCodes">
</div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="/authors/sign_up">Sign up</a>
            <a class="btn btn-sm btn-outline-secondary" href="/authors/sign_out" method="post">Logout</a>
            <%= button_to 'Sign out', destroy_author_session_path, method: :delete %>
          </div>
        </div>
      </header>


      <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="#">About</a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="/posts">All Posts</a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#">Connect with Me!</a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#">Portfolio</a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="/posts/new">New Post</a>
          <a class="p-2 text-muted" href="#"></a>
        </nav>


  <div class="container-two">
      <%= yield %>
  </div>

  

<footer class="branding">
  <small>&copy; 2021 <strong>MicheTek, LLC</strong> - Built with Ruby on Rails, JS, Boostrap</small>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>